info:
  component: Platform Router (Zuul)
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: 6080

management:
  port: 6081

logging:
  level: INFO

logging:
  level:
    com:
      netflix: WARN


eureka:
  #Region where eureka is deployed -For AWS specify one of the AWS regions, for other datacenters specify a arbitrary string
  #indicating the region.This is normally specified as a -D option (eg) -Deureka.region=us-east-1
  region: default

  #Name of the application to be identified by other services (TODO: default using spring)
  name: zuul

  #Virtual host name by which the clients identifies this service
  vipAddress: zuul

  #The port where the service will be running and serving requests (TODO: default using spring)
  #port: 7080

  #For eureka clients running in eureka server, it needs to connect to servers in other zones
  preferSameZone: false

  #Change this if you want to use a DNS based lookup for determining other eureka servers. For example
  #of specifying the DNS entries, check the eureka-client-test.properties, eureka-client-prod.properties
  shouldUseDns: false

  us-east-1:
    availabilityZones: default

  serviceUrl:
    default: http://localhost/eureka/v2/

  healthCheckUrlPath: /health

  statusPageUrlPath: /info