info:
  component: Platform Sample Backend
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: 7080

logging:
  level: INFO

logging:
  level:
    com:
      netflix: WARN

eureka:
  client:
    #Region where eureka is deployed -For AWS specify one of the AWS regions, for other datacenters specify a arbitrary string
    #indicating the region.
    region: default


    #For eureka clients running in eureka server, it needs to connect to servers in other zones
    preferSameZone: false

    us-east-1:
      availabilityZones: default

    serviceUrl:
       defaultZone: http://localhost:8761/eureka/

  instance:
    #Virtual host name by which the clients identifies this service
    #virtualHostName: ${spring.application.name}