info:
  component: Platform Sample Frontend

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: 9080

#TODO: set all this as defaults during autoconfigure
samplebackendservice:
  ribbon:
    #listOfServers: localhost:7080
    #NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList

    # the eureka vipAddress of the target service (Disabled)
    #DeploymentContextBasedVipAddresses: samplebackendservice

    # Max number of retries on the same server (excluding the first try)
    MaxAutoRetries: 1

    # Max number of next servers to retry (excluding the first server)
    MaxAutoRetriesNextServer: 1

    # Whether all operations can be retried for this client
    OkToRetryOnAllOperations: true

    # Interval to refresh the server list from the source
    ServerListRefreshInterval: 2000

    # Connect timeout used by Apache HttpClient
    ConnectTimeout: 3000

    # Read timeout used by Apache HttpClient
    ReadTimeout: 3000

eureka:
  client:
    #Region where eureka is deployed -For AWS specify one of the AWS regions, for other datacenters specify a arbitrary string
    #indicating the region.This is normally specified as a -D option (eg) -Deureka.region=us-east-1
    region: default

    #For eureka clients running in eureka server, it needs to connect to servers in other zones
    preferSameZone: false

    us-east-1:
      availabilityZones: default

    serviceUrl:
      default: http://localhost:8080/eureka/v2/
      defaultZone: http://localhost:8080/eureka/v2/

  instance:
    #Virtual host name by which the clients identifies this service
    virtualHostName: ${spring.application.name}
    aSGName: sampleApps


# disable Ribbon's cicruit breaker and rely soley on Hystrix.
# this helps to avoid confusion.
# see https://github.com/Netflix/ribbon/issues/15
niws:
  loadbalancer:
    availabilityFilteringRule:
      filterCircuitTripped: false

logging:
  level: INFO

logging:
  level:
    com:
      netflix: WARN